#!/bin/sh
case "$(file -Lb --mime-type -- "$1")" in
  image/*)
    chafa -f sixel -s "$2x$3" --polite on -t 1 -w 3 "$1"
    ;;
  video/*)
    ffmpegthumbnailer -i "$1" -o /tmp/thumb.png -s 0 -t 0
    chafa -f sixel -s "$2x$3" --polite on -t 1 -w 3 /tmp/thumb.png
    ;;
  text/*)
    cat "$1"
    ;;
esac
